### ISSUE TITLE
Add community code of conduct

### ISSUE THREAD

**Issue by brylie** [apinf/openapi-designer#193]
Our GitHub project community profile is nearly complete:

![screenshot_20170626_101515](https://user-images.githubusercontent.com/17307/27528289-6eebff3c-5a58-11e7-915e-8c38ca778055.png)

We are simply missing a code of conduct for community contributors, including the core developers.

# Goal
* [ ] Discuss the importance of having a code of conduct in an open source project. 
* [x] Review at least two community code of conduct documents from other open source projects. 
* [x] Determine the best-fit code of conduct for our project/community.
